# Generated by Django 2.2.6 on 2021-08-08 17:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20210807_2157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'author')},
        ),
        migrations.RemoveField(
            model_name='follow',
            name='lock_repeat',
        ),
    ]
