# Generated by Django 2.2.16 on 2021-09-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210926_1746'),
        ('posts', '0006_auto_20210808_2011'),
    ]

    operations = [
    ]
