# Generated by Django 2.2.16 on 2021-09-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_merge_20210928_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['following'], 'verbose_name': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['title'], 'verbose_name': 'Сообщество', 'verbose_name_plural': 'Сообщества'},
        ),
    ]
